Fix databricks using original py filename
schipholgroup/takeoff pull request #84
Opened 2021-03-30 10:00 UTC by basvdl

## Summary:

In the previous PR a feature was added to upload an artefact using the original filename. This impacts the deploy to databricks step. This PR implements the same flag.

## Breaking Change:

None

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] There is no commented out code in this PR.
  - [x] There are no new TODOs in this PR

If exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated

2021-03-31 07:09 UTC, danielvdende requested changes
2 minor comments on the docs :)

2021-03-31 07:09 UTC, danielvdende commented on docs/_deployment-steps/deploy_to_databricks.md
> +| `jobs[].use_original_python_filename` [optional] | If you uploaded multiple unique Python files using the `use_original_python_filename` in the `publish_artifact` job, use this flag here too. Only
nit: could you make the brackets around `optional` parentheses? :D that's what the other optional ones have too.

2021-03-31 07:09 UTC, danielvdende commented on docs/_deployment-steps/deploy_to_databricks.md
> +| `jobs[].use_original_python_filename` [optional] | If you uploaded multiple unique Python files using the `use_original_python_filename` in the `publish_artifact` job, use this flag here too. Only
On a general note: would it be a good idea to add an example here? For me, the explanation is good, but I still don't quite understand the impact on the naming of my files. I think adding an example somewhere in the docs would help.

2021-04-08 13:16 UTC, basvdl commented on docs/_deployment-steps/deploy_to_databricks.md
> +| `jobs[].use_original_python_filename` [optional] | If you uploaded multiple unique Python files using the `use_original_python_filename` in the `publish_artifact` job, use this flag here too. Only
This is a bit random throughout the project. But for this file I changed it to parentheses.

2021-04-08 13:16 UTC, basvdl commented on docs/_deployment-steps/deploy_to_databricks.md
> +| `jobs[].use_original_python_filename` [optional] | If you uploaded multiple unique Python files using the `use_original_python_filename` in the `publish_artifact` job, use this flag here too. Only
I have added a table that explains the behaviour of the flag. The table is also added to the publish-artifact docs

2021-04-19 06:40 UTC, danielvdende approved these changes

2021-04-19 06:40 UTC, merged